git mv images/grid_list/button_titlebar_bl_press.png unused/images/grid_list/button_titlebar_bl_press.png
git mv images/grid_list/button_titlebar_b_press.png unused/images/grid_list/button_titlebar_b_press.png
git mv images/grid_list/button_titlebar_br_press.png unused/images/grid_list/button_titlebar_br_press.png
git mv images/grid_list/button_titlebar_l_press.png unused/images/grid_list/button_titlebar_l_press.png
git mv images/grid_list/button_titlebar_press.png unused/images/grid_list/button_titlebar_press.png
git mv images/grid_list/button_titlebar_r_press.png unused/images/grid_list/button_titlebar_r_press.png
git mv images/grid_list/button_titlebar_tl.png unused/images/grid_list/button_titlebar_tl.png
git mv images/grid_list/button_titlebar_tl_press.png unused/images/grid_list/button_titlebar_tl_press.png
git mv images/grid_list/button_titlebar_t.png unused/images/grid_list/button_titlebar_t.png
git mv images/grid_list/button_titlebar_t_press.png unused/images/grid_list/button_titlebar_t_press.png
git mv images/grid_list/button_titlebar_tr.png unused/images/grid_list/button_titlebar_tr.png
git mv images/grid_list/button_titlebar_tr_press.png unused/images/grid_list/button_titlebar_tr_press.png
