git mv images/Popup_Menu/button_cm_bl.png archived/images/Popup_Menu/button_cm_bl.png
git mv images/Popup_Menu/button_cm_b.png archived/images/Popup_Menu/button_cm_b.png
git mv images/Popup_Menu/button_cm_br.png archived/images/Popup_Menu/button_cm_br.png
git mv images/Popup_Menu/button_cm_l.png archived/images/Popup_Menu/button_cm_l.png
git mv images/Popup_Menu/button_cm.png archived/images/Popup_Menu/button_cm.png
git mv images/Popup_Menu/button_cm_r.png archived/images/Popup_Menu/button_cm_r.png
git mv images/Popup_Menu/button_cm_tl.png archived/images/Popup_Menu/button_cm_tl.png
git mv images/Popup_Menu/button_cm_t.png archived/images/Popup_Menu/button_cm_t.png
git mv images/Popup_Menu/button_cm_tr.png archived/images/Popup_Menu/button_cm_tr.png
git mv images/Popup_Menu/cm_popup_bkgrd.png archived/images/Popup_Menu/cm_popup_bkgrd.png
git mv images/Popup_Menu/cm_popup_whole.png archived/images/Popup_Menu/cm_popup_whole.png
git mv images/Popup_Menu/cm_titlebar_divider.png archived/images/Popup_Menu/cm_titlebar_divider.png
