git mv  images/Icons/checkbox_off_3line.png archived/images/Icons
git mv  images/Icons/checkbox_on_3line.png archived/images/Icons
git mv  images/Icons/icon_arrow_tch_toolbar.png archived/images/Icons
git mv  images/Icons/icon_back_button_tb.png archived/images/Icons
git mv  images/Icons/icon_check_3line.png archived/images/Icons
git mv  images/Icons/icon_close_button_tb.png archived/images/Icons
git mv  images/Icons/icon_delete_tch_text_entry_huge.png archived/images/Icons
git mv  images/Icons/icon_help_button_tb.png archived/images/Icons
git mv  images/Icons/icon_home_button_tb.png archived/images/Icons
git mv  images/Icons/icon_mode_alarm_on.png archived/images/Icons
git mv  images/Icons/icon_mode_edit_playlist.png archived/images/Icons
git mv  images/Icons/icon_mode_pause.png archived/images/Icons
git mv  images/Icons/icon_mode_playlist.png archived/images/Icons
git mv  images/Icons/icon_mode_play.png archived/images/Icons
git mv  images/Icons/icon_mode_sleep_on.png archived/images/Icons
git mv  images/Icons/icon_mode_stop.png archived/images/Icons
git mv  images/Icons/icon_more_info_tb.png archived/images/Icons
git mv  images/Icons/icon_more_tb.png archived/images/Icons
git mv  images/Icons/icon_mute_on.png archived/images/Icons
git mv  images/Icons/icon_mute.png archived/images/Icons
git mv  images/Icons/icon_nplay_button_tb.png archived/images/Icons
git mv  images/Icons/icon_nplay_list_tb.png archived/images/Icons
git mv  images/Icons/icon_nplay_off.png archived/images/Icons
git mv  images/Icons/icon_password_dot_tch.png archived/images/Icons
git mv  images/Icons/icon_period_tch.png archived/images/Icons
git mv  images/Icons/icon_playlist_mode.png archived/images/Icons
git mv  images/Icons/icon_playlist_remove_sel_del.png archived/images/Icons
git mv  images/Icons/icon_plist_add_3line.png archived/images/Icons
git mv  images/Icons/icon_plist_add.png archived/images/Icons
git mv  images/Icons/icon_plist_remove_3line_del.png archived/images/Icons
git mv  images/Icons/icon_plist_remove_3line.png archived/images/Icons
git mv  images/Icons/icon_plist_remove_del.png archived/images/Icons
git mv  images/Icons/icon_plist_remove_off_del.png archived/images/Icons
git mv  images/Icons/icon_plist_remove.png archived/images/Icons
git mv  images/Icons/icon_popup_box_alarm.png archived/images/Icons
git mv  images/Icons/icon_popup_box_fwd.png archived/images/Icons
git mv  images/Icons/icon_popup_box_mode_playlist.png archived/images/Icons
git mv  images/Icons/icon_popup_box_pause.png archived/images/Icons
git mv  images/Icons/icon_popup_box_play.png archived/images/Icons
git mv  images/Icons/icon_popup_box_power.png archived/images/Icons
git mv  images/Icons/icon_popup_box_repeat_off.png archived/images/Icons
git mv  images/Icons/icon_popup_box_repeat.png archived/images/Icons
git mv  images/Icons/icon_popup_box_repeat_song.png archived/images/Icons
git mv  images/Icons/icon_popup_box_rew.png archived/images/Icons
git mv  images/Icons/icon_popup_box_shuffle_album.png archived/images/Icons
git mv  images/Icons/icon_popup_box_shuffle_off.png archived/images/Icons
git mv  images/Icons/icon_popup_box_shuffle.png archived/images/Icons
git mv  images/Icons/icon_popup_box_skip_limit.png archived/images/Icons
git mv  images/Icons/icon_popup_box_sleep_15.png archived/images/Icons
git mv  images/Icons/icon_popup_box_sleep_30.png archived/images/Icons
git mv  images/Icons/icon_popup_box_sleep_45.png archived/images/Icons
git mv  images/Icons/icon_popup_box_sleep_60.png archived/images/Icons
git mv  images/Icons/icon_popup_box_sleep_90.png archived/images/Icons
git mv  images/Icons/icon_popup_box_sleep_off.png archived/images/Icons
git mv  images/Icons/icon_popup_box_stop.png archived/images/Icons
git mv  images/Icons/icon_popup_box_volume_bar.png archived/images/Icons
git mv  images/Icons/icon_popup_box_volume_mute.png archived/images/Icons
git mv  images/Icons/icon_power_button_tb.png archived/images/Icons
git mv  images/Icons/icon_repeat_on.png archived/images/Icons
git mv  images/Icons/icon_repeat_song.png archived/images/Icons
git mv  images/Icons/icon_return_off.png archived/images/Icons
git mv  images/Icons/icon_return_on.png archived/images/Icons
git mv  images/Icons/icon_shuffle_album.png archived/images/Icons
git mv  images/Icons/icon_shuffle_on.png archived/images/Icons
git mv  images/Icons/icon_toolbar_ban_dis.png archived/images/Icons
git mv  images/Icons/icon_toolbar_ban_off.png archived/images/Icons
git mv  images/Icons/icon_toolbar_ban_on.png archived/images/Icons
git mv  images/Icons/icon_toolbar_control.png archived/images/Icons
git mv  images/Icons/icon_toolbar_fav_remove.png archived/images/Icons
git mv  images/Icons/icon_toolbar_ffwd_dis.png archived/images/Icons
git mv  images/Icons/icon_toolbar_ffwd.png archived/images/Icons
git mv  images/Icons/icon_toolbar_ipod.png archived/images/Icons
git mv  images/Icons/icon_toolbar_love_dis.png archived/images/Icons
git mv  images/Icons/icon_toolbar_pause_dis.png archived/images/Icons
git mv  images/Icons/icon_toolbar_pause.png archived/images/Icons
git mv  images/Icons/icon_toolbar_play_dis.png archived/images/Icons
git mv  images/Icons/icon_toolbar_play.png archived/images/Icons
git mv  images/Icons/icon_toolbar_power_dis.png archived/images/Icons
git mv  images/Icons/icon_toolbar_power_on.png archived/images/Icons
git mv  images/Icons/icon_toolbar_power.png archived/images/Icons
git mv  images/Icons/icon_toolbar_repeat_off.png archived/images/Icons
git mv  images/Icons/icon_toolbar_repeat_on.png archived/images/Icons
git mv  images/Icons/icon_toolbar_repeat_song_on.png archived/images/Icons
git mv  images/Icons/icon_toolbar_rew.png archived/images/Icons
git mv  images/Icons/icon_toolbar_search.png archived/images/Icons
git mv  images/Icons/icon_toolbar_shuffle_album_on.png archived/images/Icons
git mv  images/Icons/icon_toolbar_shuffle_dis.png archived/images/Icons
git mv  images/Icons/icon_toolbar_shuffle_off.png archived/images/Icons
git mv  images/Icons/icon_toolbar_shuffle_on.png archived/images/Icons
git mv  images/Icons/icon_toolbar_slacker_fav_dis.png archived/images/Icons
git mv  images/Icons/icon_toolbar_slacker_fav_off.png archived/images/Icons
git mv  images/Icons/icon_toolbar_slacker_fav_on.png archived/images/Icons
git mv  images/Icons/icon_toolbar_stop.png archived/images/Icons
git mv  images/Icons/icon_toolbar_vol_down_dis.png archived/images/Icons
git mv  images/Icons/icon_toolbar_vol_down.png archived/images/Icons
git mv  images/Icons/icon_toolbar_vol_up_dis.png archived/images/Icons
git mv  images/Icons/icon_toolbar_vol_up.png archived/images/Icons
git mv  images/Icons/icon_wireless_0_3line.png archived/images/Icons
git mv  images/Icons/icon_wireless_0.png archived/images/Icons
git mv  images/Icons/icon_wireless_0_shadow.png archived/images/Icons
git mv  images/Icons/icon_wireless_1_3line.png archived/images/Icons
git mv  images/Icons/icon_wireless_1_shadow.png archived/images/Icons
git mv  images/Icons/icon_wireless_2_3line.png archived/images/Icons
git mv  images/Icons/icon_wireless_3_3line.png archived/images/Icons
git mv  images/Icons/icon_wireless_4_3line.png archived/images/Icons
git mv  images/Icons/icon_wireless_cantconnect.png archived/images/Icons
git mv  images/Icons/icon_wireless_disabled.png archived/images/Icons
git mv  images/Icons/icon_wireless_waiting.png archived/images/Icons
git mv  images/Icons/icon_world_tch_toolbar.png archived/images/Icons
git mv  images/Icons/paginate_off.png archived/images/Icons
git mv  images/Icons/paginate_on.png archived/images/Icons
git mv  images/Icons/radiobutton_off_3line.png archived/images/Icons
git mv  images/Icons/radiobutton_on_3line.png archived/images/Icons
git mv  images/Icons/selection_add_3line_off.png archived/images/Icons
git mv  images/Icons/selection_play_3line_off.png archived/images/Icons
git mv  images/Icons/selection_right_3line_off.png archived/images/Icons
git mv  images/Icons/selection_right_3line_on.png archived/images/Icons
git mv  images/Icons/sel_right_textentry_3ft.png archived/images/Icons
git mv  images/Icons/sel_right_textentry.png archived/images/Icons
git mv  images/Icons/text_3dots_info_rem.png archived/images/Icons
git mv  images/Icons/text_3line_3dots_off.png archived/images/Icons
git mv  images/Icons/text_3line_3dots_on.png archived/images/Icons
git mv  images/Icons/text_5line_3dots_off.png archived/images/Icons
git mv  images/Icons/text_5line_3dots_on.png archived/images/Icons
