git mv  images/Buttons/button_arrow_tb_press.png archived/images/Buttons
git mv  images/Buttons/button_delete_text_entry_ref.png archived/images/Buttons
git mv  images/Buttons/button_delete_whole_press_ref.png archived/images/Buttons
git mv  images/Buttons/button_delete_whole_ref.png archived/images/Buttons
git mv  images/Buttons/button_end_tb_press.png archived/images/Buttons
git mv  images/Buttons/button_np_end_tb_press.png archived/images/Buttons
git mv  images/Buttons/button_nplaying_tb_press.png archived/images/Buttons
git mv  images/Buttons/button_spacebar_tb_press.png archived/images/Buttons
git mv  images/Buttons/button_tbar_whole.png archived/images/Buttons
git mv  images/Buttons/button_tbar_whole_press.png archived/images/Buttons
git mv  images/Buttons/kbrd_button_corner_press_tl.png archived/images/Buttons
git mv  images/Buttons/kbrd_corner_press_tl.png archived/images/Buttons
git mv  images/Buttons/kbrd_corner_press_t.png archived/images/Buttons
git mv  images/Buttons/keybrd_button_spacebar_pres.png archived/images/Buttons
git mv  images/Buttons/keybrd_cnr_button_press_se.png archived/images/Buttons
git mv  images/Buttons/keybrd_cnr_button_press_sw.png archived/images/Buttons
git mv  images/Buttons/keybrd_cnr_button_press_tl.png archived/images/Buttons
git mv  images/Buttons/keybrd_cnr_button_press_tr.png archived/images/Buttons
git mv  images/Buttons/keybrd_ne_button_press_ref.png archived/images/Buttons
git mv  images/Buttons/keybrd_nw_button_press_ref.png archived/images/Buttons
git mv  images/Buttons/keybrd_popup_button_press.png archived/images/Buttons
git mv  images/Buttons/keybrd_se_button_press_ref.png archived/images/Buttons
git mv  images/Buttons/keybrd_sw_button_press_ref.png archived/images/Buttons
