git mv  images/UNOFFICIAL/album_noartwork_184.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/http_43.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/http_64.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/http.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/icon_album_noartwork_190.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/icon_toolbar_ffwd.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/icon_toolbar_pause.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/icon_toolbar_play.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/icon_toolbar_rew.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/icon_toolbar_vol_up.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/menu_box_fixed_2c.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/tch_volume_slider.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/viz_progress_fill_l.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/viz_progress_fill.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/viz_progress_fill_r.png archived/images/UNOFFICIAL
git mv  images/UNOFFICIAL/viz_progress_slider.png archived/images/UNOFFICIAL
